### PR TITLE
Player on ended handler

### PR DESCRIPTION
**Pull request by micuat**
I added a handler resolving https://github.com/Jisuanke/CodeMirror-Record/issues/21

I didn't add any other events as currently there is no GUI component and it makes no sense to add onplay/onpause/onseek etc.

### CODE REVIEW

**Comment by haoranyu** [comment]
Now this way of adding a specific event is a bit hard-coded. You can see if the following information allows us to provide a better event binding experience in a more "eventish" way just like the interface provided by [CodeMirror](https://codemirror.net/doc/manual.html#on).

> I didn't add any other events as currently there is no GUI component and it makes no sense to add onplay/onpause/onseek etc.

In the implementation of `CodePlay`, there are already functions provided as `play`, `pause`, `seek`. It may be better to directly add `on` and `off` methods to bind `play`, `pause`, `seek` and `end` events in CodePlay.

Then we may use them like

```javascript
const codePlayer = new CodePlay(playCodeMirror, {
  maxPause: 3000,
  extraActivityHandler: (extraOperation) => {
    console.log(extraOperation);
  },
});
codePlayer.on('play', () => {
  console.log('play function called');
});
codePlayer.on('pause', () => {
  console.log('pause function called');
});
codePlayer.on('seek', (seekTime) => {
  console.log('seek function called to', seekTime);
});
codePlayer.on('end', () => {
  console.log('play ends');
});

codePlayer.off('play', offFunc);
codePlayer.off('pause', offFunc);
codePlayer.off('seek', offFunc);
codePlayer.off('end', offFunc);
```

**Comment by micuat** [comment]
I see. I will check how feasible it is. Also event handler for every recorded event may be useful too (or should it be received from codemirror instead?)

**Comment by haoranyu** [comment]
> I see. I will check how feasible it is. Also event handler for every recorded event may be useful too (or should it be received from codemirror instead?)

I suggest that only events related to the player should be added at this time. For events that can be directly captured in CodeMirror, I suggest to leave it to CodeMirror. 

Btw, if relevant specific needs arise later, we can separately evaluate whether to add new events.

**Comment by haoranyu** [comment]
The feature is now supported. Ref #31

**Pull request closed without merging**
